Вёрска всех страниц по БЭМ
htmlacademy-adaptive/1982775-cat-energy-26 pull request #2
Opened 2022-08-05 08:58 UTC by Geozoyka

2022-08-05 17:56 UTC, Zakamsky requested changes
Работа проделана большая, с вниманием к деталям.
Немного подкачали заголовки: 

![image](https://user-images.githubusercontent.com/35491086/183127509-ab93a1e8-eaa9-41aa-a407-c8b3c65f4ede.png)
h2 - это прямо заголовок секции сайта, он великоват для товаров, а показать еще, это ведь не подзаголовок последнего товара верно?

![image](https://user-images.githubusercontent.com/35491086/183128621-7db425f4-4e5c-40cf-8c3e-449b43a64d45.png)
тут вроде бы все понятно, я там в коде еще подписал этот момент.

В БЭМ разобрался хорошо, модификаторы используются по месту и корректно. не увидел только миксинов...
з.ы. нашел миксины в кнопках - все отлично!

давай поправим разметку перед тем как идти к стилям.

пожалуйста проверяй себя всякий раз когда правишь разметку (даже если класс какой то изменил), в валидаторе и в сервисе для проверки БЭМ, вот [в этом](https://yoksel.github.io/html-tree/)

2022-08-05 17:56 UTC, Zakamsky commented on source/index.html
> +    <p class="main-header__cat">CAT<span class="main-header__energy">ENERGY</span></p>
я не понял что это за текст...

2022-08-05 17:56 UTC, Zakamsky commented on source/index.html
> +        <h2 class="advantages__title">набор массы</h2>
вот тут странно, вроде одинаковые по логике заголовки, но разного уровня.
И по структуре на 57й строке это подзаголовок всей секции, но одного уровня с заголовком секции...

2022-08-05 17:56 UTC, Zakamsky commented on source/index.html
> +      <a class="social-list__sponsor" href="#">HTML Academy</a>
иии... этот элемент совсем не потомок блока `.social-list` да и по логике совсем не его часть.
может отдельным блоком его сделать? или элементом футера?

2022-08-05 17:56 UTC, Zakamsky commented on source/catalog.html
> +        </article>
а изображение товара это просто неважная часть оформления, которая просто для красоты?

2022-08-05 17:56 UTC, Zakamsky commented on source/catalog.html
> +      </div>
`.more` - это ка бы блок у нас, но в нем нет элементов, зато они есть рядом...
наверное тут нужна любая обертка, хоть тот же артикл, ему этот класс блока а заголовку - `.more__title`

2022-08-05 17:56 UTC, Zakamsky commented on source/catalog.html
> +        <h2 class="visually-hidden">Наш адрес.</h2>
тут какая то путаница с уровнями заголовков...
![image](https://user-images.githubusercontent.com/35491086/183128194-fae6bb0d-134f-4230-b5d6-62ffb43cb96d.png)
как будто "дилеры" это часть "доп товаров" (что неверное конечно, это ведь след. секция), а "адрес" прямо блок выше уровнем... (последний вообще врят ли заголовок, тут одного хватит вполне)

2022-08-05 17:56 UTC, Zakamsky commented on source/form.html
> +                <input class="form__age-input" id="age" type="text" placeholder="7">
точно ли это текстовые поля?
возраст - молодой
вес - средний

2022-08-05 17:56 UTC, Zakamsky commented on source/form.html
> +              </li>
Что бы связать вместе поля радио, надо указать им одинаковое `name` и разные `value`
А сейчас я могу выбрать все три, но не могу снять выбор, а так быть не должно.
![image](https://user-images.githubusercontent.com/35491086/183132822-318f4417-4651-43b4-81db-d79e2c8b2f7d.png)

2022-08-05 17:56 UTC, Zakamsky commented on source/form.html
> +          <span>* — Обязательные поля</span>
и последнее замечание по форме - сейчас все обязательные поля совсем не обязательные.
что это работало нужен специальный атрибут `required` который не позволит отправить форму если поле с ним пустое.

2022-08-05 18:44 UTC, Geozoyka commented on source/index.html
> +    <p class="main-header__cat">CAT<span class="main-header__energy">ENERGY</span></p>
извиняюсь забыл удалить с прежней идеи

2022-08-05 18:51 UTC, Geozoyka commented on source/index.html
> +        <h2 class="advantages__title">набор массы</h2>
по невнимательности. Исправил на h3

2022-08-05 18:55 UTC, Geozoyka commented on source/index.html
> +      <a class="social-list__sponsor" href="#">HTML Academy</a>
сделал просто класс sponsor

2022-08-05 19:00 UTC, Geozoyka commented on source/catalog.html
> +        </article>
Тут я ступил, увлёкся семантикой

2022-08-05 19:25 UTC, Geozoyka commented on source/catalog.html
> +      </div>
Обернул в артикл

2022-08-06 08:47 UTC, Geozoyka commented on source/form.html
> +              </li>
сделал

2022-08-06 08:48 UTC, Geozoyka commented on source/form.html
> +                <input class="form__age-input" id="age" type="text" placeholder="7">
изменил поля на number и добавил min   max

2022-08-06 08:48 UTC, Geozoyka commented on source/form.html
> +          <span>* — Обязательные поля</span>
да думал об этом но так и забыл

2022-08-06 15:22 UTC, Zakamsky approved these changes
Замечательная работа над ошибками. Принято!

2022-08-06 16:22 UTC, merged